version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - API_PORT=3000
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=redis://redis:6379
      - SUPABASE_PROJECT_URL=${SUPABASE_PROJECT_URL}
      - SUPABASE_JWKS_URL=${SUPABASE_JWKS_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - BCRA_API_BASE_URL=${BCRA_API_BASE_URL}
      - BCRA_API_KEY=${BCRA_API_KEY}
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - redis
    command: npm run start:dev

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  redis_data:
