export const MAX_GUARANTOR_ATTEMPTS = 3;
export const CASE_GUARANTOR_EVALUATION_ENGINE = 'ZCORE_BCRA_V1';

/** Solo antes/después del riel de análisis; post-NOSIS debe pasar primero por otro flujo a PENDING_GUARANTOR_ANALYSIS. */
export const ALLOWED_CASE_STATUSES_FOR_GUARANTOR_EVALUATION = [
  'OFFER_SENT',
  'PENDING_GUARANTOR_ANALYSIS',
] as const;

export const CASE_GUARANTOR_ERRORS = {
  CASE_NOT_FOUND: 'CASE_NOT_FOUND',
  INVALID_GUARANTOR_CUIT: 'INVALID_GUARANTOR_CUIT',
  GUARANTOR_CUIT_MATCHES_APPLICANT_CUIT:
    'GUARANTOR_CUIT_MATCHES_APPLICANT_CUIT',
  CASE_DOES_NOT_REQUIRE_GUARANTOR: 'CASE_DOES_NOT_REQUIRE_GUARANTOR',
  CASE_STATUS_INVALID: 'CASE_STATUS_INVALID',
  MAX_GUARANTOR_ATTEMPTS_REACHED: 'MAX_GUARANTOR_ATTEMPTS_REACHED',
  DUPLICATE_GUARANTOR_CUIT: 'DUPLICATE_GUARANTOR_CUIT',
  APPROVED_GUARANTOR_PENDING_CEO_DECISION:
    'APPROVED_GUARANTOR_PENDING_CEO_DECISION',
  NO_APPROVED_GUARANTOR_TO_RESOLVE: 'NO_APPROVED_GUARANTOR_TO_RESOLVE',
} as const;

/** Transición interna de caso a APROBADO_FINAL + oferta ACCEPTED (solo desde PENDING_NOSIS). */
export const CASE_APROBADO_FINAL_ERRORS = {
  CASE_NOT_FOUND: 'CASE_NOT_FOUND',
  CASE_STATUS_INVALID: 'CASE_STATUS_INVALID',
  CURRENT_OFFER_NOT_FOUND: 'CURRENT_OFFER_NOT_FOUND',
} as const;

/** Marca evaluación automática BCRA; distinto de decisión manual CEO. */
export const CASE_GUARANTOR_SYSTEM_REVIEWER = 'system';
