export const MAX_GUARANTOR_ATTEMPTS = 3;
export const CASE_GUARANTOR_EVALUATION_ENGINE = 'ZCORE_BCRA_V1';

export const ALLOWED_CASE_STATUSES_FOR_GUARANTOR_EVALUATION = [
  'OFFER_SENT',
  'PENDING_GUARANTOR_ANALYSIS',
] as const;

export const CASE_GUARANTOR_ERRORS = {
  CASE_NOT_FOUND: 'CASE_NOT_FOUND',
  INVALID_GUARANTOR_CUIT: 'INVALID_GUARANTOR_CUIT',
  CASE_NOT_REQUIRING_GUARANTOR: 'CASE_NOT_REQUIRING_GUARANTOR',
  CASE_NOT_READY_FOR_GUARANTOR_EVALUATION:
    'CASE_NOT_READY_FOR_GUARANTOR_EVALUATION',
  MAX_GUARANTOR_ATTEMPTS_REACHED: 'MAX_GUARANTOR_ATTEMPTS_REACHED',
  DUPLICATE_GUARANTOR_CUIT: 'DUPLICATE_GUARANTOR_CUIT',
} as const;
