export const ContractDataErrors = {
  // Initiate
  CASE_NOT_FOUND: 'CASE_NOT_FOUND',
  CASE_STATUS_INVALID: 'CASE_STATUS_INVALID',
  // Submit
  TOKEN_NOT_FOUND: 'TOKEN_NOT_FOUND',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_ALREADY_USED: 'TOKEN_ALREADY_USED',
  TOKEN_SUBJECT_MISMATCH: 'TOKEN_SUBJECT_MISMATCH',
  INVALID_EMAIL_FORMAT: 'INVALID_EMAIL_FORMAT',
  INVALID_CBU_CVU_FORMAT: 'INVALID_CBU_CVU_FORMAT',
  INVALID_ALIAS_FORMAT: 'INVALID_ALIAS_FORMAT',
  LOCALIDAD_NOT_FOUND: 'LOCALIDAD_NOT_FOUND',
  GUARANTOR_NOT_FOUND: 'GUARANTOR_NOT_FOUND',
} as const;
