export const ContractsErrors = {
  CASE_NOT_FOUND: 'CASE_NOT_FOUND',
  CASE_NOT_READY_FOR_CONTRACT: 'CASE_NOT_READY_FOR_CONTRACT',
  ACCEPTED_OFFER_NOT_FOUND: 'ACCEPTED_OFFER_NOT_FOUND',
  ACTIVE_CONTRACT_ALREADY_EXISTS: 'ACTIVE_CONTRACT_ALREADY_EXISTS',
  INVALID_SIGN_PROVIDER: 'INVALID_SIGN_PROVIDER',
  SIGNATURA_RESPONSE_INVALID: 'SIGNATURA_RESPONSE_INVALID',
  WEBHOOK_NOT_AUTHENTIC: 'WEBHOOK_NOT_AUTHENTIC',
  CASE_CONTRACT_NOT_FOUND: 'CASE_CONTRACT_NOT_FOUND',
  CONTRACT_IN_TERMINAL_STATE: 'CONTRACT_IN_TERMINAL_STATE',
  BIOMETRIC_VALIDATION_FAILED: 'BIOMETRIC_VALIDATION_FAILED',
  IDENTITY_VALIDATION_FAILED: 'IDENTITY_VALIDATION_FAILED',
  EVIDENCE_INCOMPLETE: 'EVIDENCE_INCOMPLETE',
  LOAN_ALREADY_EXISTS: 'LOAN_ALREADY_EXISTS',
  REFINANCE_RULE_BROKEN: 'REFINANCE_RULE_BROKEN',
  PROVIDER_BLOCKING_ERROR: 'PROVIDER_BLOCKING_ERROR',
} as const;

export type ContractsErrorCode =
  (typeof ContractsErrors)[keyof typeof ContractsErrors];
