/** Etapas oficiales del lead alineadas a `lead_stage` en DB. */
export enum LeadStage {
  NEED_CONSENT = 'NEED_CONSENT',
  NEED_DATA = 'NEED_DATA',
  DATA_COMPLETE = 'DATA_COMPLETE',
  WAITING_REQUESTED_AMOUNT = 'WAITING_REQUESTED_AMOUNT',
  WAITING_REQUESTED_AMOUNT_MANUAL_REVIEW = 'WAITING_REQUESTED_AMOUNT_MANUAL_REVIEW',
  WAITING_CEO = 'WAITING_CEO',
  OFFER_SENT = 'OFFER_SENT',
  REJECTED = 'REJECTED',
}
